name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: Start test server
      run: |
        docker-compose build
        docker-compose run --rm app ls
        echo 'hoge'
        docker-compose run --rm app ls bin
        docker-compose run --rm app pwd
        docker-compose run --rm app ./bin/setup
        docker-compose run --rm app ./bin/test
